### ISSUE TITLE
What's the reason of mouting files?

### ISSUE THREAD

**Issue by orlovmyk** [DefGuard/deployment#21]
https://github.com/DefGuard/deployment/blob/c599c0ad06cd31adeaa4ababc6ed15530cbd1b60/docker-compose/docker-compose.yaml#L20

https://github.com/DefGuard/deployment/blob/c599c0ad06cd31adeaa4ababc6ed15530cbd1b60/docker-compose/docker-compose.yaml#L21

https://github.com/DefGuard/deployment/blob/c599c0ad06cd31adeaa4ababc6ed15530cbd1b60/docker-compose/docker-compose.yaml#L22

I have faced this issue too many times when Docker shim can't mount file in directory during first time setup, is this necessary? Maybe better to mount whole directory?

**Comment by teon** [comment]
@wojcik91 can you relate?

**Comment by wojcik91** [comment]
Hi @orlovmyk 
Thank you for pointing this out. 
Are you using the one-line install script or just the `docker-compose.yaml` file? Does the `Caddyfile` exist?

Mounting the whole directory would not solve this particular issue, since I expect the problematic part is the `Caddyfile` which should be mounted into a separate directory. And if the `Caddyfile` doesn't exist there's no reason to start Caddy itself.

Current iteration of the `docker-compose.yaml` file was prepared with the install script in mind and I can now see that it can cause issues for users who want to just use the file itself for manual deployment. I'll have to update it to avoid further confusion.

**Comment by orlovmyk** [comment]
@wojcik91 Thanks for reply, yep I am not using one-line script to install as far as I wanted to dig a little bit deeper. Anyways I moved caddy outside of the docker-compose, so it's not a problem for me anymore, but you are right It needs to be provided in docs.

Also as solution you can create simple Caddyfile inside repo, that will be overridden by one-install script. For example reverse-proxy to `core` only as base.

By the way project is 🔥
